version: "3.9"


services:
    testtask_app:
        container_name: testtask_app
        build: .
        env_file:
            - .env_app
        command: bash -c "cd app/ && celery -A test_task worker | python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/home/python/app
        links:
            - testtask_db
            - testtask_redis
        depends_on:
            - testtask_db
            - testtask_redis
        ports:
            - 8000:8000

    testtask_db:
        image: postgres:latest
        container_name: testtask_db
        restart: 'on-failure'
        env_file:
            - .env_db
        ports:
            - 5432:5432

    testtask_redis:
        image: redis:latest
        container_name: testtask_redis
        env_file:
            - .env_redis
        restart: "on-failure"
        command: redis-server
        # command: bash -c "redis-server --appendonly yes"
        ports:
            - 6379:6379
